### ISSUE TITLE
buendia-reconfigure networking (with no changes) can bring down the wifi connection

### ISSUE THREAD

**Issue by zestyping** [projectbuendia/buendia#221]
On a reference deployment, I ran `buendia-reconfigure -f networking` and it brought down networking even though the configuration hadn't changed.

As I remember fuzzily from the time, it seemed that `NETWORKING_DHCP_DNS_SERVER` was 1, which caused the script to take the "Turning on DHCP and DNS server; disabling DHCP client" path.  But we still want to be a DHCP client, because the WiFi AP is the DHCP server in our reference setup.

I think in this state, everything (including DHCP) works properly on boot and the server gets an address, but attempting to reconfigure while up relinquishes the IP address.

**Comment by schuyler** [comment]
I understand this to be the intended behavior for `buendia-reconfigure -f networking` -- the `-f` flag forces reconfiguration. The main interface needs then to be brought down so that it can definitely be brought up with the right settings.

The script shouldn't disable dhcpcd unless we have a `NETWORKING_DHCP_RANGE` set, as described in the [networking documentation](https://github.com/projectbuendia/buendia/blob/dev/packages/buendia-networking/README.md). I'll submit a PR that fixes this.

**Comment by zestyping** [comment]
It is not the intended behaviour for `buendia-reconfigure -f networking` to (finally) result in a change to the networking configuration of the machine if the network settings in the `site` directory have not changed.  It may interrupt the network briefly during the reconfiguration process, but it should not bring down the network permanently (which is the incident that this issue is about).

**Comment by schuyler** [comment]
Ok, my forthcoming PR should fix that, at least.
